version: '3.9'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs,s3
    ports:
      - 4566:4566
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '54321:5432'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'