export enum JobStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  FINISHED = 'FINISHED',
  FAILED = 'FAILED',
}


export enum JobDependencyStatus {
  RUNNING = 'RUNNING',
  FINISHED = 'FINISHED',
  FAILED = 'FAILED'
}

export enum JobDependencyTrace {
  REG_METADATA = 'REG_METADATA',
  REG_DOWNLOADED = 'REG_DOWNLOADED',
  REP_METADATA = 'REP_METADATA',
  REP_COMMITS = 'REP_COMMITS',
  REP_ISSUES = 'REP_ISSUES',
  REP_RELEASES = 'REP_RELEASES',
  REP_VULNERABILITIES = 'REP_VULNERABILITIES'
}
